### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by 3noch** [layer-3-communications/reflex-dom-helpers#3]
@andrewthad I noticed some unresolved PRs and this project does not build with more recent reflex-dom versions. Are you still maintaining this?

**Comment by andrewthad** [comment]
Oh my, I had not noticed the PRs. I don't get PR notifications for repos I maintain, and I've never been able to get github to do this (it only notifies me when someone opens an issue). That aside, I don't use this library anymore, but I'll give you a commit bit in case you'd like to take it over, and I'm happy to push releases to hackage (assuming that the newer version of reflex eventually makes it to hackage).

**Comment by andrewthad** [comment]
Invite link: https://github.com/layer-3-communications/reflex-dom-helpers/invitations

**Comment by 3noch** [comment]
@andrewthad Thanks! I would like to use this library and get it working again.

I'm curious if you're now using a different approach to Reflex-DOM templates or if you're no longer using Reflex-DOM at all? I only ask because if you had something better/different for Reflex-DOM I'd be interested in hearing about it.

**Comment by andrewthad** [comment]
I'm still using `reflex-dom`. But, instead of using this, I just use `el` and write out the element name as the first argument.

**Comment by 3noch** [comment]
@andrewthad Aha. You've fully assimilated. ;) I still struggle to bring myself to do that, hence my interest in this library. Thanks for the access. I hope to have a new release ready for you next week.

**Comment by daig** [comment]
@andrewthad I'm curious what the benefit of using `el` directly (other than needing to write all these combinators, which has already been done). Is it a namespacing issue?

**Comment by andrewthad** [comment]
@daig There's not a huge benefit to it. It's just me being lazy.

**Comment by jappeace** [comment]
I like the compiler complain if I type shit wrong, and fewer chars on screen. But yeah probably not worth the hours I put in.

**Comment by chessai** [comment]
Closing. Library is maintained.
