### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by jappeace** [layer-3-communications/reflex-dom-helpers#8]
Hi could you please make a new release because reflex 0.5 came out on hackage and I want to depend on this library with another library.

Thanks

**Comment by andrewthad** [comment]
I’ve added you as a github maintainer.  Is your username on Hackage the same?

**Comment by jappeace** [comment]
Thanks, it's: `Jappie` on hackage

**Comment by andrewthad** [comment]
You have been added.

**Comment by jappeace** [comment]
Done: https://hackage.haskell.org/package/reflex-dom-helpers-0.2.0.1
